In [1]:
import pandas as pd
df1 = pd.read_csv(r'C:\Users\brian\Desktop\JUNSOO\exhibition\data\temp.csv' , encoding ='cp949')
df2 = pd.read_csv(r'C:\Users\brian\Desktop\JUNSOO\exhibition\data\final_data.csv' , encoding = "euc-kr")
df1 = df1.loc[df1['전체학생수']!= 0 , :]

In [2]:
print(df1.columns.tolist())

col_use = ['key' , '전체학생수' , '상담실적(외부상담전문가)'
    , '연간1인당 보건실이용건수' , '교수학습공간 일반교실'
    , '교수학습공간 특별교실' 
    , '교수학습공간 수준별교실' ,'참여학생수-동아리?학생자치활동' , '참여학생수-또래활동' 
           , '참여학생수-교육주간 활동' , '참여학생수-기타 학교폭력 예방활동'
           , '일반직계' , '별정직계(2018년이후)' , '기타직계(2019년이후)' ,'전문상담교사(계)' ,
           '수석교사(계)' , '체력 1등급 (%)' , '교육청금액' , '학교교육시설 보수확충금액', '수목시설및 재산금액'
            ,'도서및 물품금액','금전및 유가증권금액', '자치단체금액' ,'상담실적(내부상담전문가)'
           ]
df1 = df1[col_use]

['key', '지역', '정보공시 학교코드', '학교명', '교과교실제(지정?운영)', '자율학교(지정?운영)', '수준별 수업(운영)', '전체학생수', '연간1인당 보건실이용건수', '일반직계', '별정직계(2018년이후)', '기타직계(2019년이후)', '특수학급 학급당 학생수', '순회학급 학급당 학생수', '수업교원 1인당 학생수', '체육장 개방여부', '체육관 개방여부', '강당 개방여부', '일반교과교실 개방여부', '특별교실 개방여부', '시청각실 개방여부', '수석교사(계)', '전문상담교사(계)', '사서교사(계)', '보건교사(계)', '영양교사(계)', '체력 1등급 (%)', '체력 2등급 (%)', '체력 3등급 (%)', '체력 4등급 (%)', '체력 5등급 (%)', '교육청금액', '자치단체금액', '보호자금액', '보호자비율', '금전및 유가증권금액', '도서및 물품금액', '수목시설및 재산금액', '학교교육시설 보수확충금액', '교육용기자재 및도서금액', '학교체육학예 활동금액', '학생복지및 자치활동지원금액', '지도교사수-동아리?학생자치활동', '지도교사수-또래활동', '지도교사수-교육주간 활동', '지도교사수-기타 학교폭력 예방활동', '참여학생수-동아리?학생자치활동', '참여학생수-또래활동', '참여학생수-교육주간 활동', '참여학생수-기타 학교폭력 예방활동', '전체학생수_안전교육 계획 및 실시현황', '생활안전교육 시간(단위활동차시)-합계', '교통안전교육 시간(단위활동차시)-합계', '폭력예방및신변보호교육 시간(단위활동차시)-합계', '약물중독예방교육 시간(단위활동차시) - 합계 (2020년 이후)', '지능정보서비스과의존관련교육 시간(단위활동차시) - 합계 (2023년 이후)', '직업안전교육 시간(단위활동차시)-합계', '응급처치교육 시간(단위활동차시)-합계', '주 출입구 접근로 설치여부', '장애인 전용 주차구역 지정여부', '주 출입구 높이차이 제거여부', '출입구(문) 설치유무', '복도', '계단/승강기/경사로/휠체어리프트 유무', '장애인용 대변기 설치여부', '장애인용 소변기 설치여부', '점자블록 설치여부', '유도 및 안내설비 설치여부', '경보 및 피난설비 설치여부', '상담실적(내부상담전문가)', '상담실적(외부상담전문가)', '교수학습공간 일반교실', '교수학습공간 교과교실', '교수학습공간 수준별교실', '교수학습공간 특별교실', '학생자율동아리 동아리수', '창의적체험활동동아리 동아리수']

In [8]:
df1.info()
df1_copy = df1.copy()

<class 'pandas.core.frame.DataFrame'>
Index: 5456 entries, 0 to 5474
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   key                 5456 non-null   object
 1   전체학생수               5456 non-null   float64
 2   상담실적(외부상담전문가)       5456 non-null   float64
 3   연간1인당 보건실이용건수       5456 non-null   float64
 4   교수학습공간 일반교실         5456 non-null   float64
 5   교수학습공간 특별교실         5456 non-null   float64
 6   교수학습공간 수준별교실        5456 non-null   float64
 7   참여학생수-동아리?학생자치활동    5456 non-null   int64
 8   참여학생수-또래활동          5456 non-null   int64
 9   참여학생수-교육주간 활동       5456 non-null   int64
 10  참여학생수-기타 학교폭력 예방활동  5456 non-null   int64
 11  일반직계                5456 non-null   float64
 12  별정직계(2018년이후)       5456 non-null   float64
 13  기타직계(2019년이후)       5456 non-null   float64
 14  전문상담교사(계)           5456 non-null   float64
 15  수석교사(계)             5456 non-null   float64
 16  체력 1등급 (%)          5456 non-null   float64
 17  교육청금액               5456 non-null   float64
 18  학교교육시설 보수확충금액       5456 non-null   float64
 19  수목시설및 재산금액          5456 non-null   float64
 20  도서및 물품금액            5456 non-null   float64
 21  금전및 유가증권금액          5456 non-null   float64
 22  자치단체금액              5456 non-null   float64
 23  상담실적(내부상담전문가)       5456 non-null   float64
dtypes: float64(19), int64(4), object(1)
memory usage: 1.0+ MB

In [15]:
# 수치형 데이터의 범위를 바탕으로 구간을 나누어 레이블링하기
condition = ((df1['참여학생수-동아리?학생자치활동'] >=1) & (df1['참여학생수-동아리?학생자치활동'] < 53))
df1.loc[condition , '동아리_class' ] = 1
condition2 = (df1['참여학생수-동아리?학생자치활동'] >= 53)
df1.loc[condition2 , '동아리_class'] = 2
df1.loc[df1['참여학생수-동아리?학생자치활동'] == 0 ,'동아리_class'] = 0

In [16]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5456 entries, 0 to 5474
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   key                 5456 non-null   object
 1   전체학생수               5456 non-null   float64
 2   상담실적(외부상담전문가)       5456 non-null   float64
 3   연간1인당 보건실이용건수       5456 non-null   float64
 4   교수학습공간 일반교실         5456 non-null   float64
 5   교수학습공간 특별교실         5456 non-null   float64
 6   교수학습공간 수준별교실        5456 non-null   float64
 7   참여학생수-동아리?학생자치활동    5456 non-null   int64
 8   참여학생수-또래활동          5456 non-null   int64
 9   참여학생수-교육주간 활동       5456 non-null   int64
 10  참여학생수-기타 학교폭력 예방활동  5456 non-null   int64
 11  일반직계                5456 non-null   float64
 12  별정직계(2018년이후)       5456 non-null   float64
 13  기타직계(2019년이후)       5456 non-null   float64
 14  전문상담교사(계)           5456 non-null   float64
 15  수석교사(계)             5456 non-null   float64
 16  체력 1등급 (%)          5456 non-null   float64
 17  교육청금액               5456 non-null   float64
 18  학교교육시설 보수확충금액       5456 non-null   float64
 19  수목시설및 재산금액          5456 non-null   float64
 20  도서및 물품금액            5456 non-null   float64
 21  금전및 유가증권금액          5456 non-null   float64
 22  자치단체금액              5456 non-null   float64
 23  상담실적(내부상담전문가)       5456 non-null   float64
 24  동아리_class           5456 non-null   float64
dtypes: float64(20), int64(4), object(1)
memory usage: 1.1+ MB

In [10]:
df1.head().T

,0,1,2,3,4
key,S000003511-2021,S000003511-2022,S000003511-2023,S000003511-2024,S000003514-2021
전체학생수,614.0,611.0,612.0,610.0,625.0
상담실적(외부상담전문가),0.0,0.0,0.0,0.0,20.0
연간1인당 보건실이용건수,1.1,7.4,14.8,15.6,2.3
교수학습공간 일반교실,28.0,28.0,28.0,28.0,24.0
교수학습공간 특별교실,12.0,12.0,12.0,12.0,21.0
교수학습공간 수준별교실,0.0,0.0,0.0,0.0,0.0
참여학생수-동아리?학생자치활동,0,0,52,52,0
참여학생수-또래활동,8,8,610,610,0
참여학생수-교육주간 활동,0,600,610,610,0
참여학생수-기타 학교폭력 예방활동,330,600,0,0,0
일반직계,1.0,1.0,1.0,1.0,3.0
별정직계(2018년이후),0.0,0.0,0.0,0.0,0.0
기타직계(2019년이후),10.0,14.0,14.0,13.0,7.0
전문상담교사(계),0.0,0.0,0.0,0.0,0.0
수석교사(계),0.0,0.0,0.0,0.0,0.0
체력 1등급 (%),0.05193,0.15814,0.014019,0.074766,0.074766
교육청금액,187721.0,240361.0,370443.0,418437.0,315141.0
학교교육시설 보수확충금액,0.0,0.0,0.0,56600000.0,0.0
수목시설및 재산금액,0.0,0.0,0.0,0.0,0.0
도서및 물품금액,5800000.0,0.0,0.0,1395709.0,0.0
금전및 유가증권금액,0.0,2000000.0,0.0,56650000.0,0.0
자치단체금액,187724.0,233190.0,275640.0,303126.0,73102.0
상담실적(내부상담전문가),280.0,265.0,750.0,750.0,252.0

In [3]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5456 entries, 0 to 5455
Data columns (total 39 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   key        5456 non-null   object
 1   지역         5456 non-null   object
 2   정보공시 학교코드  5456 non-null   object
 3   학교명        5456 non-null   object
 4   x1         5456 non-null   object
 5   x2         5456 non-null   object
 6   x3         5456 non-null   object
 7   x4         5456 non-null   float64
 8   x5         5456 non-null   float64
 9   x6         5456 non-null   int64
 10  x7         5456 non-null   int64
 11  x8         5456 non-null   int64
 12  x9         5456 non-null   float64
 13  x10        5456 non-null   float64
 14  x11        5456 non-null   float64
 15  x12        5456 non-null   float64
 16  x13        5456 non-null   float64
 17  x14        5456 non-null   float64
 18  x15        5456 non-null   float64
 19  x16        5456 non-null   float64
 20  x17        5456 non-null   object
 21  x18        5456 non-null   object
 22  x19        5456 non-null   object
 23  x20        5456 non-null   object
 24  x21        5456 non-null   object
 25  x22        5456 non-null   object
 26  x23        5456 non-null   object
 27  x24        5456 non-null   object
 28  x25        5456 non-null   object
 29  x26        5456 non-null   object
 30  x27        5456 non-null   object
 31  x28        5456 non-null   object
 32  x29        5456 non-null   object
 33  x30        5456 non-null   object
 34  y          5456 non-null   float64
 35  s1         5456 non-null   float64
 36  s2         5456 non-null   float64
 37  s3         5456 non-null   float64
 38  s4         5456 non-null   float64
dtypes: float64(15), int64(3), object(21)
memory usage: 1.6+ MB

In [17]:
# 1) 학교평가 공통지표
# 수준별 교육과정 , 학생이해 노력, 전문적 공동체 구축
# 교육활동지원을 위한 행정, 재정적 지원
# 수석교사의 수
df1['t1'] = df1['전체학생수']
df1['t2'] = df1['수석교사(계)']

# 2) 목적 사업비
# 기초자치단체 이전수입

df1['t3'] = df1['연간1인당 보건실이용건수']
df1['t4'] = df1['별정직계(2018년이후)'] + df1['기타직계(2019년이후)']
df1['t5'] = df1['동아리_class']


# 3) 진로성숙도
# 진로체험경험 , 학교 진로지원 , 학업성취도 ,부모와 자녀간의 의사소통
df1['t6'] = df1['상담실적(외부상담전문가)'] + df1['상담실적(내부상담전문가)']
df1['t7'] = df1['전문상담교사(계)']
#

In [18]:
df1_pay_score = df1.loc[:,'t1':'t7']
df1_pay_score.head().T

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

df1_pay_score["y2"] = scaler.fit_transform(df1_pay_score).sum(axis = 1).tolist()

In [19]:
df1_key = pd.DataFrame(df1['key'])
df1_pay_score = pd.concat([df1_pay_score , df1_key] , axis = 1)
df1_pay_score

         t1   t2    t3    t4   t5     t6   t7        y2              key
0     614.0  0.0   1.1  10.0  0.0  280.0  0.0  0.506671  S000003511-2021
1     611.0  0.0   7.4  14.0  0.0  265.0  0.0  0.610257  S000003511-2022
2     612.0  0.0  14.8  14.0  1.0  750.0  0.0  1.216626  S000003511-2023
3     610.0  0.0  15.6  13.0  1.0  750.0  0.0  1.199750  S000003511-2024
4     625.0  0.0   2.3   7.0  0.0  272.0  0.0  0.457204  S000003514-2021
...     ...  ...   ...   ...  ...    ...  ...       ...              ...
5469  150.0  0.0   6.7   8.0  0.0  423.0  1.0  0.633897  S010006545-2022
5470  210.0  0.0   8.1   9.0  2.0  284.0  1.0  1.666865  S010006545-2023
5471  263.0  0.0   7.3   9.0  2.0  609.0  2.0  2.069285  S010006545-2024
5472  263.0  0.0   7.3   9.0  0.0    0.0  2.0  0.978728  S010006553-2022
5474  297.0  0.0   9.9  10.0  1.0  260.0  1.0  1.231197  S010006558-2023

[5456 rows x 9 columns]

In [20]:
school_sc = df2['y']

In [21]:
school_sc = pd.DataFrame(school_sc)
df2_key = df2['key']
school_sc = pd.concat([df2_key , school_sc] , axis = 1)
school_sc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5456 entries, 0 to 5455
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   key     5456 non-null   object
 1   y       5456 non-null   float64
dtypes: float64(1), object(1)
memory usage: 85.4+ KB

In [22]:
plz = pd.merge(school_sc , df1_pay_score , how = "outer" , on = 'key')

In [23]:
plz.info()

plz.drop(columns = 'key' , inplace = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5456 entries, 0 to 5455
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   key     5456 non-null   object
 1   y       5456 non-null   float64
 2   t1      5456 non-null   float64
 3   t2      5456 non-null   float64
 4   t3      5456 non-null   float64
 5   t4      5456 non-null   float64
 6   t5      5456 non-null   float64
 7   t6      5456 non-null   float64
 8   t7      5456 non-null   float64
 9   y2      5456 non-null   float64
dtypes: float64(9), object(1)
memory usage: 426.4+ KB

In [24]:
plz.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5456 entries, 0 to 5455
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   y       5456 non-null   float64
 1   t1      5456 non-null   float64
 2   t2      5456 non-null   float64
 3   t3      5456 non-null   float64
 4   t4      5456 non-null   float64
 5   t5      5456 non-null   float64
 6   t6      5456 non-null   float64
 7   t7      5456 non-null   float64
 8   y2      5456 non-null   float64
dtypes: float64(9)
memory usage: 383.8 KB

In [25]:
plz.corr(method= 'pearson')

,y,t1,t2,t3,t4,t5,t6,t7,y2
y,1.000000,-0.037759,0.043069,-0.129973,-0.009667,-0.028163,0.074750,0.050576,-0.000437
t1,-0.037759,1.000000,0.071943,-0.207371,0.202189,-0.014982,0.058707,0.102876,0.392030
t2,0.043069,0.071943,1.000000,-0.033805,0.084046,-0.023272,0.041027,0.008787,0.310162
t3,-0.129973,-0.207371,-0.033805,1.000000,-0.013555,0.162388,0.076155,-0.016067,0.096070
t4,-0.009667,0.202189,0.084046,-0.013555,1.000000,-0.010153,-0.022356,-0.136609,0.249877
t5,-0.028163,-0.014982,-0.023272,0.162388,-0.010153,1.000000,0.062003,-0.003025,0.731525
t6,0.074750,0.058707,0.041027,0.076155,-0.022356,0.062003,1.000000,0.153041,0.235158
t7,0.050576,0.102876,0.008787,-0.016067,-0.136609,-0.003025,0.153041,1.000000,0.424659
y2,-0.000437,0.392030,0.310162,0.096070,0.249877,0.731525,0.235158,0.424659,1.000000